# Import libraries
library(GSVA)
library(vegan)
library(ggplot2)
library(ggrepel)
library(dplyr)
library(tidyr)

# Load gene expression dataset
datasets <- read.csv("data/ovary_logreg_datasets_df_top_100_genes.csv", 
                     row.names = 1, 
                     check.names = FALSE,
                     stringsAsFactors = FALSE)

# Define gene signatures for different cell types
genelist <- list(
  "Fallopian Tube Normal_ciliated epithelial cell" = c('TFF3',
                                                       'TPPP3',
                                                       'CAPS',
                                                       'C1orf194',
                                                       'TMEM190',
                                                       'FAM183A',
                                                       'C20orf85',
                                                       'C9orf24',
                                                       'AL357093.2',
                                                       'RSPH1',
                                                       'PIFO',
                                                       'CETN2',
                                                       'SNTN',
                                                       'CAPSL',
                                                       'AGR3',
                                                       'AGR2',
                                                       'DYNLRB2',
                                                       'C9orf116',
                                                       'DNAAF1',
                                                       'SCGB2A1',
                                                       'MORN2',
                                                       'PSENEN',
                                                       'MORN5',
                                                       'ZMYND10',
                                                       'CFAP157',
                                                       'C5orf49',
                                                       'CFAP126',
                                                       'SCGB1D4',
                                                       'FOXJ1',
                                                       'LRRC46',
                                                       'LRRC23',
                                                       'DYDC2',
                                                       'CFAP53',
                                                       'ODF3B',
                                                       'CRIP1',
                                                       'RIIAD1',
                                                       'FAM166B',
                                                       'LRRIQ1',
                                                       'CDHR3',
                                                       'LDLRAD1',
                                                       'FABP6',
                                                       'CCDC78',
                                                       'TXN',
                                                       'MS4A8',
                                                       'IK',
                                                       'WDR54',
                                                       'TUBB4B',
                                                       'MNS1',
                                                       'TUBA4B',
                                                       'HMGN3',
                                                       'SPA17',
                                                       'CIB1',
                                                       'TEKT1',
                                                       'C9orf135',
                                                       'DRC3',
                                                       'PERP',
                                                       'FAM229B',
                                                       'CCDC17',
                                                       'EFCAB1',
                                                       'EFHC1',
                                                       'TEKT2',
                                                       'CCDC146',
                                                       'CCDC153',
                                                       'FAM216B',
                                                       'ROPN1L',
                                                       'FXYD3',
                                                       'CATSPERD',
                                                       'CCDC170',
                                                       'PRR29',
                                                       'LINC02345',
                                                       'SPAG8',
                                                       'SMIM22',
                                                       'CFAP45',
                                                       'DNALI1',
                                                       'KIF9',
                                                       'DNAH12',
                                                       'C21orf58',
                                                       'CYSTM1',
                                                       'S100A11',
                                                       'OMG',
                                                       'NME5',
                                                       'S100A6',
                                                       'MLF1',
                                                       'TMEM59',
                                                       'AC013264.1',
                                                       'AK1',
                                                       'CFAP43',
                                                       'DYNLL1',
                                                       'FAM81B',
                                                       'GET1',
                                                       'SLC44A4',
                                                       'CEP126',
                                                       'DPY30',
                                                       'RSPH9',
                                                       'NUDC',
                                                       'CFAP52',
                                                       'DPCD',
                                                       'ARMC3',
                                                       'C12orf75',
                                                       'TSPAN1'),
  "Fallopian Tube Normal_secretory cell" = c('OVGP1',
                                             'CRISP3',
                                             'CLU',
                                             'WFDC2',
                                             'SLPI',
                                             'CCL2',
                                             'MSLN',
                                             'CXCL2',
                                             'SPARCL1',
                                             'GSN',
                                             'ANXA1',
                                             'CD9',
                                             'RPS12',
                                             'MMP7',
                                             'FOSB',
                                             'CD74',
                                             'USP53',
                                             'ZFP36L1',
                                             'TM4SF1',
                                             'RPL12',
                                             'SCGB1D2',
                                             'C3',
                                             'IFITM3',
                                             'RPL31',
                                             'CLDN10',
                                             'C19orf33',
                                             'RNASET2',
                                             'RPL36A',
                                             'CLDN4',
                                             'NFKBIA',
                                             'MUC1',
                                             'DMKN',
                                             'CXCL8',
                                             'SAT1',
                                             'RPL37',
                                             'RPLP0',
                                             'SCGB3A1',
                                             'EEF1A1',
                                             'TACSTD2',
                                             'BIRC3',
                                             'RPL26',
                                             'ADIRF',
                                             'KRT19',
                                             'TPT1',
                                             'RPLP2',
                                             'RPS21',
                                             'RPL10',
                                             'RPL7A',
                                             'UGT2B7',
                                             'HLA-DRA',
                                             'SORL1',
                                             'ELF3',
                                             'KRT18',
                                             'RPS26',
                                             'CXCR4',
                                             'MGST1',
                                             'KLF5',
                                             'PART1',
                                             'SNHG8',
                                             'RPL14',
                                             'DEFB1',
                                             'TTYH1',
                                             'RPS8',
                                             'CRABP2',
                                             'ZFAS1',
                                             'RPS23',
                                             'SOD2',
                                             'MT-CO1',
                                             'RPL34',
                                             'RPL36',
                                             'ISYNA1',
                                             'SLC40A1',
                                             'WDR77',
                                             'ASS1',
                                             'CMTM6',
                                             'CYP1B1',
                                             'ARHGAP26',
                                             'RPS20',
                                             'RPL10A',
                                             'SNHG19',
                                             'RPS6',
                                             'ASRGL1',
                                             'RNASE1',
                                             'RPLP1',
                                             'COL18A1',
                                             'TNFAIP2',
                                             'MYADM',
                                             'RPL23A',
                                             'RPL13A',
                                             'RPS28',
                                             'ATF3',
                                             'RPL5',
                                             'RPS24',
                                             'RPL27A',
                                             'FBXO21',
                                             'MT-ND1',
                                             'CD24',
                                             'TFPI2',
                                             'HLA-DRB1',
                                             'RPL37A'),
  "Ovary Normal_eHormones" = c('SERPINE2',
                               'RBP1',
                               'GSTA1',
                               'CD99',
                               'VCAN',
                               'TMSB10',
                               'APOA1',
                               'IFI27',
                               'LY6E',
                               'AVPI1',
                               'FST',
                               'SPRR2F',
                               'HSD17B1',
                               'HTRA1',
                               'PRR15',
                               'IGFBP2',
                               'STMN1',
                               'TNNI3',
                               'GSTA4',
                               'LGALS1',
                               'SCARB1',
                               'FHL2',
                               'TM7SF2',
                               'AMH',
                               'PRKAR2B',
                               'HSD3B2',
                               'NDP',
                               'MT1X',
                               'HSPG2',
                               'IGFBP7',
                               'MAGED2',
                               'BAMBI',
                               'TMSB4X',
                               'S100B',
                               'MDK',
                               'STAR',
                               'PPP1R14A',
                               'ALDOA',
                               'TIMP1',
                               'S100A10',
                               'MARCKSL1',
                               'MT2A',
                               'S100A16',
                               'PRSS23',
                               'TRAPPC4',
                               'TUBB',
                               'APOE',
                               'SELENOP',
                               'MRO',
                               'FLNA',
                               'HS3ST1',
                               'INHBB',
                               'FAM78A',
                               'SH3BGRL3',
                               'FDX1',
                               'GPX3',
                               'SPARC',
                               'VIM',
                               'PRDX2',
                               'MZT2B',
                               'CYP11A1',
                               'LEFTY2',
                               'ANXA6',
                               'GREB1',
                               'DAG1',
                               'MYL9',
                               'RPS2',
                               'BEX1',
                               'HS6ST1',
                               'GRIK1',
                               'XIST',
                               'FDXR',
                               'PLA2G12A',
                               'TUBA1B',
                               'APOC1',
                               'BEX3',
                               'PEG3',
                               'ITGB1',
                               'DPYSL3',
                               'CRHBP',
                               'CHGB',
                               'SCD',
                               'CLDN11',
                               'NUP214',
                               'PLP1',
                               'SMS',
                               'CST3',
                               'IDH1',
                               'ADM',
                               'GRB14',
                               'UROS',
                               'PRELID1',
                               'SIGLEC11',
                               'RNASEH2C',
                               'TSPAN6',
                               'CSGALNACT1',
                               'GASK1B',
                               'ID3',
                               'MALAT1',
                               'MEX3B'),
  "Ovary Normal_eStromal" = c('HSPE1',
                              'HSPD1',
                              'DNAJA1',
                              'HSPA1A',
                              'CHORDC1',
                              'HSPH1',
                              'HSPA6',
                              'ZFAND2A',
                              'BAG3',
                              'CITED2',
                              'DNAJB6',
                              'EIF5',
                              'DNAJB1',
                              'CACYBP',
                              'DNAJB4',
                              'HSP90AA1',
                              'FILIP1L',
                              'CCN2',
                              'UBE2D1',
                              'SNAPC1',
                              'SGK1',
                              'NOP58',
                              'PPP1R15A',
                              'KRT18',
                              'HSP90AB1',
                              'TCP1',
                              'IQCG',
                              'CTNNAL1',
                              'MRPL18',
                              'CKS2',
                              'PHLDA1',
                              'MAFF',
                              'CD55',
                              'AHSA1',
                              'ARID5B',
                              'HSPA8',
                              'STIP1',
                              'CCN1',
                              'NECTIN2',
                              'PTGER2',
                              'TNFRSF12A',
                              'AKIRIN1',
                              'JMJD6',
                              'EGR4',
                              'UBXN8',
                              'ETF1',
                              'FGD4',
                              'ENC1',
                              'SERTAD1',
                              'RHEB',
                              'ARL5B',
                              'ARF4',
                              'LIPH',
                              'GMNN',
                              'HES1',
                              'HEY2',
                              'KLF6',
                              'SLC3A2',
                              'RSRC2',
                              'NFE2L2',
                              'PMAIP1',
                              'PRDM1',
                              'DUSP14',
                              'MCL1',
                              'DDX5',
                              'CHIC2',
                              'STK17A',
                              'PNRC2',
                              'PTP4A1',
                              'UBC',
                              'MAP1LC3B',
                              'GADD45A',
                              'ACSM3',
                              'BUD31',
                              'RBM22',
                              'CYCS',
                              'TAX1BP1',
                              'IDI1',
                              'PPP1R12B',
                              'CD59',
                              'UBE2B',
                              'HSPA1B',
                              'ZFAND5',
                              'VAPA',
                              'FKBP4',
                              'PPP2CA',
                              'SARAF',
                              'MYL12A',
                              'EPS8',
                              'CCT4',
                              'HIF1A',
                              'SFPQ',
                              'HERPUD1',
                              'KPNA2',
                              'LEPROTL1',
                              'CCT2',
                              'GADD45G',
                              'EIF1',
                              'SRSF2',
                              'F3')
)

# Set up GSVA parameters
params <- ssgseaParam(
  exprData = as.matrix(datasets),
  geneSets = genelist,
  alpha = 0.25, # Weighting parameter for gene ranks
  normalize = FALSE # Don't normalize scores by gene set size
)

# Run GSVA enrichment analysis
gsva_results <- gsva(params)
results_df <- as.data.frame(t(gsva_results))

# 1. Filter to keep only cancer samples
cancer_samples <- rownames(results_df)[grepl("Cancer|HER2\\+|ER\\+|PR\\+|TNBC", rownames(results_df))]
df <- results_df[cancer_samples, ]

# 2. Add Sample column and select relevant columns
df$Sample <- rownames(df)
df <- df[, c("Sample", colnames(df)[1:4])]
colnames(df) <- c("Sample", "Fallopian Tube Normal_ciliated epithelial cell",
                  "Fallopian Tube Normal_secretory cell",
                  "Ovary Normal_eHormones", "Ovary Normal_eStromal")

# 3. Add cancer subtype information
# df$Subtype <- sub(".*_(TNBC|HER2\\+|ER\\+|PR\\+|HER2\\+/ER\\+).*", "\\1", df$Sample)
# df$Subtype <- gsub("PR\\+", "TNBC", df$Subtype)
# df$Subtype <- gsub("HER2\\+/ER\\+", "HER2+", df$Subtype)

df$Subtype <- sub(".*_(Cancer).*", "\\1", df$Sample)

# 4. Determine tissue of origin based on maximum enrichment score
df$Origin <- colnames(df[, 2:5])[apply(df[, 2:5], 1, which.max)]

# 5. Calculate sample counts and percentages by subtype and origin
df_counts <- df %>%
  group_by(Subtype, Origin) %>%
  summarise(Count = n(), .groups = "drop") %>%
  group_by(Subtype) %>%
  mutate(Percent = Count / sum(Count) * 100)

# 6. Create stacked bar plot visualization
ggplot(df_counts, aes(x = Subtype, y = Percent, fill = Origin)) +
  geom_bar(stat = "identity") +
  labs(title = "Cancer Origin From Normal Cell Type",
       y = "Percentage (%)", x = "Cancer Type") +
  scale_fill_brewer(palette = "Set2", name = "Normal Cell Type") +
  theme_minimal()
